name: Generate Profile Trophy

on:
  schedule:
    - cron: '0 0 * * *' # Berjalan otomatis setiap jam 00:00 UTC
  workflow_dispatch: # Agar bisa dijalankan manual lewat tombol Actions

permissions:
  contents: write # Memberikan izin menulis file ke repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Trophy SVG
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          username: Hieray-dev
          theme: dracula

      - name: Commit and Push Trophy
        run: |
          git config local user.email "action@github.com"
          git config local user.name "GitHub Action"
          git add trophy.svg
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update profile trophies" && git push)
